---
#- name: Common role
#  hosts: pi
#  become: true
#  roles:
#    - common
#
#- name: Podman role
#  hosts: pi
#  become: true
#  roles:
#    - podman

- name: RR stack role
  hosts: pi
  roles:
    - rr
