---
- name: Ensure /etc/containers exists
  become: true
  become_user: root
  file:
    state: directory
    path: /etc/containers

- name: Install podman
  community.general.pacman:
    name: "podman"
    state: "present"
  loop:
    - podman
    - buildah
    - cni-plugins
    -	slirp4netns
    -	fuse-overlayfs

- name: systemctl start podman.service
  ansible.builtin.service:
    name: "podman.service"
    state: "started"
    enabled: true
  changed_when: false
  failed_when: false
