---
# https://github.com/ansible/ansible/pull/73741
- name: Creating subuid and subgid file
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: touch
    mode: 0644
  loop:
    - subuid
    - subgid

- name: Populate subuid and subgid file
  ansible.builtin.lineinfile:
    path: "/etc/{{ item }}"
    line: "{{ ansible_user }}:100000:65536"
  loop:
    - subuid
    - subgid

- name: Check if lingering is enabled
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ ansible_user }}"
  register: linger

- name: Enable lingering
  ansible.builtin.command: "loginctl enable-linger {{ ansible_user }}"
  when:
    - not linger.stat.exists

- name: Install podman
  community.general.pacman:
    name: "{{ item }}"
    state: "present"
  loop:
    - podman
    - buildah
    - cni-plugins
    - fuse-overlayfs
  notify:
    - Enable podman.socket
    - Reboot the server
