---
- name: Update locale.conf
  ansible.builtin.command: localectl set-locale LANG=en_US.UTF-8

- name: Update vconsole.conf
  ansible.builtin.command: localectl set-keymap --no-convert br-abnt2

- name: Reboot the server
  ansible.builtin.reboot:
