---
- name: Set timezone to America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo
  notify:
    - Update locale.conf
    - Update vconsole.conf

- name: Ensure a locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set hostname to inventory hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Pacman config
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: '^#{{ item }}'
    line: "{{ item }}"
  loop:
    - "Color"
    - "VerbosePkgLists"
    - "ILoveCandy"
    - "ParallelDownloads = 5"

- name: Upgrade all software
  community.general.pacman:
    update_cache: true
    upgrade: true
  notify: Reboot the server
