---
- name: Set timezone to America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo
  notify: Update clock

- name: Ensure a locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  notify:
    - Update locale.conf
    - Update vconsole.conf

- name: Set hostname to inventory hostname.
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"

- name: Upgrade all software.
  community.general.pacman:
    update_cache: true
    upgrade: true
  notify: Reboot the server
