---
- name: Enable firewalld.service
  become: true
  ansible.builtin.systemd:
    name: firewalld.service
    state: started
    enabled: true

- name: Redirect DNS, DHCP, HTTP and HTTPS to pihole
  become: true
  ansible.posix.firewalld:
    service: "{{ item }}"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop:
    - dns
    - http

- name: Redirect DNS and HTTP  to pihole
  become: true
  ansible.posix.firewalld:
    rich_rule: "{{ item }}"
    zone: public
    permanent: true
    immediate: true
    state: enabled
  loop:
    - rule family=ipv4 forward-port port=53 protocol=tcp to-port=1053
    - rule family=ipv4 forward-port port=53 protocol=udp to-port=1053
