---
- name: Create volumes folders structure if not exist
  ansible.builtin.file:
    path: "{{ home }}/{{ item }}"
    state: directory
  loop:
    - appdata/pi-hole/etc
    - appdata/pi-hole/etc-dnsmasq.d
  register: folders

- name: Podman unshare
  ansible.builtin.command: podman unshare chown -R 999:999 {{ home }}/appdata/pi-hole
  when:
    - folders.changed

- name: Firewalld config
  ansible.builtin.include_tasks: firewalld.yaml

- name: Create pod for containers
  containers.podman.podman_pod:
    name: pihole
    infra_name: pihole-infra
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "8082:80/tcp"
  notify: Enable pod-pihole.service

- name: Run pi-hole
  containers.podman.podman_container:
    name: pi-hole
    pod: pihole
    image: docker.io/pihole/pihole:latest
    restart_policy: unless-stopped
    env:
      INTERFACE: tap0
      TZ: America/Sao_Paulo
      FTLCONF_LOCAL_IPV4: 192.168.15.52
      WEBPASSWORD: 123
    volume:
      - "{{ home }}/appdata/pi-hole/etc:/etc/pihole"
      - "{{ home }}/appdata/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d"

- name: Create pod for containers
  containers.podman.podman_pod:
    name: pihole
    infra_name: pihole-infra
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
      - "8082:80/tcp"
    generate_systemd:
      restart_policy: always
      path: "{{ home }}/.config/systemd/user"
