- name: Create volumes folders structure if not exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: a=,a+rX,u+w,g+w
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
  loop:
    - /data/torrents
    - /data/media/movies
    - /data/media/tv
    - /podman/appdata/radarr
    - /podman/appdata/sonarr
    - /podman/appdata/prowlarr
    - /podman/appdata/bazarr
    - /podman/appdata/rutorrent
    - /podman/appdata/jellyfin

- name: Podman unshare chown
  ansible.builtin.command: podman unshare chown -R 1000:1000 /data /podman

- name: Create pod for containers
  containers.podman.podman_pod:
    name: rr
    ports:
      - 8096:8096 # jellyfin
      - 7359:7359/udp # jellyfin
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 6767:6767 # bazarr
      - 9696:9696 # prowlarr
      - 8080:80 # rutorrent
    generate_systemd:
      container_prefix: rr
      new: true
      restart_policy: always
      path: "{{ home }}/.config/systemd/user"
        #  notify: Enable pod-rr.service

- name: Run jellyfin
  containers.podman.podman_container:
    pod: rr
    name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - /podman/appdata/jellyfin:/config
      - /data/media/tv:/data/tvshows
      - /data/media/movies:/data/movies

- name: Run radarr
  containers.podman.podman_container:
    pod: rr
    name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - /podman/appdata/radarr:/config
      - /data:/data

- name: Run sonarr
  containers.podman.podman_container:
    pod: rr
    name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - /podman/appdata/sonarr:/config
      - /data:/data

- name: Run bazarr
  containers.podman.podman_container:
    pod: rr
    name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - /podman/appdata/bazarr:/config
      - /data/media:/data/media

- name: Run prowlarr
  containers.podman.podman_container:
    pod: rr
    name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:nightly
    env:
      TZ: America/Sao_Paulo
    volume:
      - /podman/appdata/prowlarr:/config

- name: Run rutorrent
  containers.podman.podman_container:
    pod: rr
    name: rutorrent
    image: ghcr.io/linuxserver/rutorrent:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - /podman/appdata/rutorrent:/config
      - /data/torrents:/data/torrents
