- name: Create volumes folders structure if not exist
  ansible.builtin.file:
    path: "{{ home }}/{{ item }}"
    state: directory
  loop:
    - data/torrents
    - data/media/movies
    - data/media/tv
    - appdata/radarr
    - appdata/sonarr
    - appdata/prowlarr
    - appdata/bazarr
    - appdata/rutorrent
    - appdata/jellyfin
  notify: Podman unshare

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: Create pod for containers
  containers.podman.podman_pod:
    name: rr
    infra_name: rr-infra
    ports:
      - 8096:8096 # jellyfin
      - 7359:7359/udp # jellyfin
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 6767:6767 # bazarr
      - 9696:9696 # prowlarr
      - 8080:80 # rutorrent
  notify: Enable pod-rr.service

- name: Run jellyfin
  containers.podman.podman_container:
    pod: rr
    name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - "{{ home }}/appdata/jellyfin:/config"
      - "{{ home }}/data/media/tv:/data/tvshows"
      - "{{ home }}/data/media/movies:/data/movies"

- name: Run radarr
  containers.podman.podman_container:
    pod: rr
    name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - "{{ home }}/appdata/radarr:/config"
      - "{{ home }}/data:/data"

- name: Run sonarr
  containers.podman.podman_container:
    pod: rr
    name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - "{{ home }}/appdata/sonarr:/config"
      - "{{ home }}/data:/data"

- name: Run bazarr
  containers.podman.podman_container:
    pod: rr
    name: bazarr
    image: cr.hotio.dev/hotio/bazarr:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - "{{ home }}/appdata/bazarr:/config"
      - "{{ home }}/data/media:/data/media"

- name: Run prowlarr
  containers.podman.podman_container:
    pod: rr
    name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:nightly
    env:
      TZ: America/Sao_Paulo
    volume:
      - "{{ home }}/appdata/prowlarr:/config"

- name: Run rutorrent
  containers.podman.podman_container:
    pod: rr
    name: rutorrent
    image: ghcr.io/linuxserver/rutorrent:latest
    env:
      TZ: America/Sao_Paulo
    volume:
      - "{{ home }}/appdata/rutorrent:/config"
      - "{{ home }}/data/torrents:/data/torrents"

- name: Create systemd file for pod and containers
  containers.podman.podman_pod:
    name: rr
    infra_name: rr-infra
    ports:
      - 8096:8096 # jellyfin
      - 7359:7359/udp # jellyfin
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 6767:6767 # bazarr
      - 9696:9696 # prowlarr
      - 8080:80 # rutorrent
    generate_systemd:
      new: true
      path:
        "{{ home }}/.config/systemd/user"
